version: '3'

services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  python-3.10-prompt_leakage_probing:
    image: mcr.microsoft.com/devcontainers/python:3.10
    container_name: prompt_leakage_probing-${USER}-python-3.10
    volumes:
      - ../:/workspaces/prompt_leakage_probing:cached
    command: sleep infinity

    env_file:
      - ./devcontainer.env
    security_opt:
      - no-new-privileges:true
    networks:
      - prompt_leakage_probing-network

networks:
  prompt_leakage_probing-network:
    name: prompt_leakage_probing-${USER}-network
